package mr.bpm.mbanking.dot;

import java.math.BigDecimal;
import java.util.Date;

public class PApiGetCifAccountsCursor {
	public BigDecimal olBranchCode;
	public String osIsoCyCode;
	public BigDecimal olCurrencyCode;
	public BigDecimal olGlCode;
	public BigDecimal olCifSubNo;
	public String osCifName;
	public BigDecimal olSlNo;
	public String osAddReference;
	public String osGlNameEng;
	public String osGlNameArab;
	public String osBriefNameEng;
	public String osBriefNameArab;
	public String osLongNameEng;
	public String osLongNameArab;
	public BigDecimal odecFcBal;
	public BigDecimal odecFcAvailBal;
	public BigDecimal odecCvBal;
	public BigDecimal odecCvAvailBal;
	public String osStatus;
	public Date odOpenDate;
	public Date odMaturity;
	public BigDecimal olCardNumber;
	public String osCardType;
	public BigDecimal odecHoldAmount;
	public BigDecimal odecToDayCreditAmount;
	public BigDecimal odecToDayDebitAmount;
	public BigDecimal odecToDayFloatAmount;
	public String osAccountType;
	public String osOfficerName;
	public BigDecimal olNoAccounts;
	public BigDecimal olMaturityDays;
	public String osPftTo;
	public String osRenew;
	public Date odDate;
	public BigDecimal olPtRate;
	public BigDecimal olTrfCy;
	public BigDecimal olTrfGl;
	public BigDecimal olTrfCif;
	public BigDecimal olTrfSl;
	public String osModarabaType;
	public BigDecimal olBankId;
	public String osBankAccId;
	public String osAdress1Eng;
	public String osAdress2Eng;
	public String osAdress3Eng;
	public String osCityEng;
	public BigDecimal olCountry;
	public BigDecimal olDealNo;
	public String osDealCustomNo;
	public BigDecimal olStateCode;
	public String osPostCode;
	public String osGmiFlag;
	public BigDecimal olErrorCode;
	public String osErrorDesc;
}
