package mr.bpm.mbanking.dot;

import java.math.BigDecimal;

public class PApiCreateAccountIn {
	public BigDecimal alChannelId;
	public String asUserId;
	public String asMachineName;
	public BigDecimal alAPiCode;
	public String adtDate; 
	public BigDecimal alCompCode;
	public BigDecimal alBranchCode;
	public String asCurrencyCode; 
	public BigDecimal alGlCode;
	public BigDecimal alCifSubNo;
	public String asTellerId;
	public String asRenew;
	public BigDecimal alTrfBr;
	public BigDecimal alTrfCy;
	public BigDecimal alTrfGl;
	public BigDecimal alTrfCif;
	public BigDecimal alTrfSl;
	public String asTrfAddRef;
	public String asPftPostTo; 
	public BigDecimal alProfitBr;
	public BigDecimal alProfitCy;
	public BigDecimal alProfitGl;
	public BigDecimal alProfitCif;
	public BigDecimal alProfitSl;
	public String asProfitAddRef;
	public BigDecimal alMaturityGl;       
	public String asExtTrf;  
	public BigDecimal alOffBr;  
	public BigDecimal alOffCy;  
	public BigDecimal alOffGl;
	public BigDecimal aloffCIF;
	public BigDecimal aloffSL;
	public String asoffAddRef;
	public BigDecimal alTransfertAm; 
	public BigDecimal alDebitBranch;
	public BigDecimal alDebitCurrency;
	public BigDecimal alDebitGlCode;
	public BigDecimal alDebitCifSubNo;
	public BigDecimal alDebitSl;
	public String asDebitAddRef;
	public String asRemarks;
	public BigDecimal alDivCode;
	public BigDecimal alDeptCode;
	public String asReference;
	public BigDecimal alPos;
	public String asInst1;  
	public String asInst2;  
	public BigDecimal alTrxType;
	public String asStatus;
	public String asCreatedTrx;
	public String adtMaturityDate;
}
